name: "[builder] CI for releases"

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dockerhub login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_USERNAME }}
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build dockerfile (with push)
        run: |
          docker buildx build \
          --platform=linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag johanvandeweerd/unifi-controller:6.1.71
